
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package main.java.bg.fmi.quality.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2013-06-01T00:19:56.259+03:00
 * Generated source version: 2.5.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "CalculateQuantityService",
                      portName = "CalculateQuantityPort",
                      targetNamespace = "http://ws.fmi.bg.java.main/",
                      wsdlLocation = "http://localhost:8080/FoodQuantityService/services/CalculateQuantityPort?wsdl",
                      endpointInterface = "main.java.bg.fmi.quality.service.CalculateNewQuantitySEI")
                      
public class CalculateNewQuantitySEIImpl implements CalculateNewQuantitySEI {

    private static final Logger LOG = Logger.getLogger(CalculateNewQuantitySEIImpl.class.getName());

    /* (non-Javadoc)
     * @see main.java.bg.fmi.quality.service.CalculateNewQuantitySEI#calculateQuantity(double  arg0 ,)double  arg1 ,)double  arg2 ,)double  arg3 ,)double  arg4 ,)double  arg5 )*
     */
    public java.lang.String calculateQuantity(double arg0,double arg1,double arg2,double arg3,double arg4,double arg5) { 
        LOG.info("Executing operation calculateQuantity");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        try {
            java.lang.String _return = "_return-1715124824";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
