
package main.java.bg.fmi.quality.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2013-06-01T00:19:56.191+03:00
 * Generated source version: 2.5.10
 * 
 */
public final class CalculateNewQuantitySEI_CalculateQuantityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.fmi.bg.java.main/", "CalculateQuantityService");

    private CalculateNewQuantitySEI_CalculateQuantityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculateQuantityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalculateQuantityService ss = new CalculateQuantityService(wsdlURL, SERVICE_NAME);
        CalculateNewQuantitySEI port = ss.getCalculateQuantityPort();  
        
        {
        System.out.println("Invoking calculateQuantity...");
        double _calculateQuantity_arg0 = 0.12692465434815414;
        double _calculateQuantity_arg1 = 0.2810100715058126;
        double _calculateQuantity_arg2 = 0.6772415025901193;
        double _calculateQuantity_arg3 = 0.6612737677068232;
        double _calculateQuantity_arg4 = 0.23746952069060423;
        double _calculateQuantity_arg5 = 0.5638910225498465;
        java.lang.String _calculateQuantity__return = port.calculateQuantity(_calculateQuantity_arg0, _calculateQuantity_arg1, _calculateQuantity_arg2, _calculateQuantity_arg3, _calculateQuantity_arg4, _calculateQuantity_arg5);
        System.out.println("calculateQuantity.result=" + _calculateQuantity__return);


        }

        System.exit(0);
    }

}
