package main.java.bg.fmi.quality.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2013-06-01T00:19:56.278+03:00
 * Generated source version: 2.5.10
 * 
 */
@WebService(targetNamespace = "http://ws.fmi.bg.java.main/", name = "CalculateNewQuantitySEI")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculateNewQuantitySEI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "calculateQuantity", targetNamespace = "http://ws.fmi.bg.java.main/", className = "main.java.bg.fmi.quality.service.CalculateQuantity")
    @WebMethod
    @ResponseWrapper(localName = "calculateQuantityResponse", targetNamespace = "http://ws.fmi.bg.java.main/", className = "main.java.bg.fmi.quality.service.CalculateQuantityResponse")
    public java.lang.String calculateQuantity(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        double arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        double arg5
    );
}
