
package main.java.bg.fmi.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.10
 * Sat Jun 01 00:00:34 EEST 2013
 * Generated source version: 2.5.10
 */

@XmlRootElement(name = "calculateQuantity", namespace = "http://ws.fmi.bg.java.main/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculateQuantity", namespace = "http://ws.fmi.bg.java.main/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4", "arg5"})

public class CalculateQuantity {

    @XmlElement(name = "arg0")
    private double arg0;
    @XmlElement(name = "arg1")
    private double arg1;
    @XmlElement(name = "arg2")
    private double arg2;
    @XmlElement(name = "arg3")
    private double arg3;
    @XmlElement(name = "arg4")
    private double arg4;
    @XmlElement(name = "arg5")
    private double arg5;

    public double getArg0() {
        return this.arg0;
    }

    public void setArg0(double newArg0)  {
        this.arg0 = newArg0;
    }

    public double getArg1() {
        return this.arg1;
    }

    public void setArg1(double newArg1)  {
        this.arg1 = newArg1;
    }

    public double getArg2() {
        return this.arg2;
    }

    public void setArg2(double newArg2)  {
        this.arg2 = newArg2;
    }

    public double getArg3() {
        return this.arg3;
    }

    public void setArg3(double newArg3)  {
        this.arg3 = newArg3;
    }

    public double getArg4() {
        return this.arg4;
    }

    public void setArg4(double newArg4)  {
        this.arg4 = newArg4;
    }

    public double getArg5() {
        return this.arg5;
    }

    public void setArg5(double newArg5)  {
        this.arg5 = newArg5;
    }

}

