
package main.java.bg.fmi.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.10
 * Sat Jun 01 00:00:34 EEST 2013
 * Generated source version: 2.5.10
 */

@XmlRootElement(name = "calculateQuantityResponse", namespace = "http://ws.fmi.bg.java.main/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculateQuantityResponse", namespace = "http://ws.fmi.bg.java.main/")

public class CalculateQuantityResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

