
package main.java.bg.fmi.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.10
 * Sat Jun 01 00:11:18 EEST 2013
 * Generated source version: 2.5.10
 */

@XmlRootElement(name = "takeFood", namespace = "http://ws.fmi.bg.java.main/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "takeFood", namespace = "http://ws.fmi.bg.java.main/")

public class TakeFood {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

