package main.java.bg.fmi.ui;

import java.awt.List;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.LinkedList;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.xml.namespace.QName;

import main.java.bg.fmi.food.service.TakeFoodImplService;
import main.java.bg.fmi.food.service.TakeFoodSEI;
import main.java.bg.fmi.quality.service.CalculateNewQuantitySEI;
import main.java.bg.fmi.quality.service.CalculateQuantityService;

/**
 * 
 * @author Cannibal
 */
public class Foods extends javax.swing.JFrame {

	private static final QName SERVICE_NAME = new QName(
			"http://ws.fmi.bg.java.main/", "TakeFoodImplService");
	private static final QName QUANTITY_NAME = new QName(
			"http://ws.fmi.bg.java.main/", "CalculateQuantityService");

	public Foods() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		txtFilSearchFood = new javax.swing.JTextField();
		btnSearch = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		lblFoodName = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		lblProtein = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		lblCarbs = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		lblFats = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		lblEnergy = new javax.swing.JLabel();
		txtFldQuantity = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtAreaDescription = new javax.swing.JTextArea();
		jLabel7 = new javax.swing.JLabel();
		btnRecalculate = new javax.swing.JButton();
		lblCurrentDate = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		txtFilSearchFood
				.setToolTipText("Въведете името на храната, която искате да търсите");

		btnSearch.setText("Search");
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});

		jLabel1.setText("Име на храната");

		lblFoodName.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel2.setText("Описание");

		jLabel3.setText("Белтък");

		lblProtein.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel4.setText("Въглехидрати");
		jLabel4.setToolTipText("Съдържанието на въглехидрати в избраната храна");

		lblCarbs.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel6.setText("Мазнини");

		lblFats.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel5.setText("Енергийност");

		lblEnergy.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		txtAreaDescription.setColumns(20);
		txtAreaDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		txtAreaDescription.setRows(5);
		jScrollPane1.setViewportView(txtAreaDescription);

		jLabel7.setText("Количество");

		btnRecalculate.setText("Recalculate");
		btnRecalculate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRecalculateActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														216,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		txtFilSearchFood,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		216,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		btnSearch))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		216,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jLabel7,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtFldQuantity)
																				.addComponent(
																						btnRecalculate,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						45,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						lblProtein,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						lblCarbs,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						73,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel4))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						lblFats,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						76,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						58,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						lblEnergy,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel5)
																								.addGap(0,
																										0,
																										Short.MAX_VALUE))))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						lblFoodName,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						216,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel1))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		lblCurrentDate,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		81,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						btnSearch)
																				.addComponent(
																						txtFilSearchFood,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		lblFoodName,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		15,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														lblCurrentDate,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														23,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel7)
																.addGap(9, 9, 9)
																.addComponent(
																		txtFldQuantity,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btnRecalculate))
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														108,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(jLabel4)
												.addComponent(jLabel6)
												.addComponent(jLabel5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														lblEnergy,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														lblFats,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														lblProtein,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														lblCarbs,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														22,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(70, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Foods.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Foods.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Foods.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Foods.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new Foods().setVisible(true);
				} catch (javax.xml.ws.WebServiceException ex) {
					JOptionPane.showMessageDialog(null,
							"Невъзможност за свързване със сървъра", "Грешка",
							JOptionPane.ERROR_MESSAGE);
					return;
				}
			}
		});

	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnRecalculate;
	private javax.swing.JButton btnSearch;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblCarbs;
	private javax.swing.JLabel lblCurrentDate;
	private javax.swing.JLabel lblEnergy;
	private javax.swing.JLabel lblFats;
	private javax.swing.JLabel lblFoodName;
	private javax.swing.JLabel lblProtein;
	private javax.swing.JTextArea txtAreaDescription;
	private javax.swing.JTextField txtFilSearchFood;
	private javax.swing.JTextField txtFldQuantity;
	// variables for Food Service
	private final URL wsdlFoodlURL = TakeFoodImplService.WSDL_LOCATION;
	private final TakeFoodImplService ss = new TakeFoodImplService(
			wsdlFoodlURL, SERVICE_NAME);
	private TakeFoodSEI port = ss.getTakeFoodImplPort();;
	// Variables for Quantity Service
	private URL wsdlQuantityURL = CalculateQuantityService.WSDL_LOCATION;
	private CalculateQuantityService cQService = new CalculateQuantityService(
			wsdlQuantityURL, QUANTITY_NAME);
	private CalculateNewQuantitySEI portQuantity = cQService
			.getCalculateQuantityPort();
	// Additional variables
	private static double oldQuantityValue = 0;

	// End of variables declaration

	// Actions

	/*
	 * Invoke new Thread when user click on the Search Button
	 */

	private void btnRecalculateActionPerformed(java.awt.event.ActionEvent evt) {
		String newQuantityString = txtFldQuantity.getText().trim();
		try {
			double newQuantityData = Double.parseDouble(newQuantityString);
			if (newQuantityData < 0) {
				JOptionPane.showMessageDialog(null,
						"Моля въведете в полето количество стойност >=0",
						"Грешка", JOptionPane.ERROR_MESSAGE);
				return;
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null,
					"Моля въведете в полето количество число", "Грешка",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				double data[] = takeQuantityInfo();
				
				fillIngrediants(portQuantity.calculateQuantity(data[0],
						data[1], data[2], data[3], data[4], data[5]));
			}
		});
	}

	void fillIngrediants(String data) {
		// data is with 5 elements not 6 !!!
		String[] dataForFilling = data.split(";");
		txtFldQuantity.setText(dataForFilling[0]);
		lblProtein.setText(dataForFilling[1]);
		lblCarbs.setText(dataForFilling[2]);
		lblFats.setText(dataForFilling[3]);
		lblEnergy.setText(dataForFilling[4]);
		oldQuantityValue = Double.parseDouble(dataForFilling[0]);
		// call fil form
		

		// Fill description field
		String[] dataForText = new String[8];
		dataForText[0] = " ";
		dataForText[1] = lblFoodName.getText();
		dataForText[2] = dataForFilling[0];
		dataForText[3] = "г.";
		dataForText[4] = dataForFilling[1];
		dataForText[5] = dataForFilling[2];
		dataForText[6] = dataForFilling[3];
		dataForText[7] = dataForFilling[4];

		txtAreaDescription.setText(generateDiscripton(dataForText));
	}

	double[] takeQuantityInfo() {
		double[] data = new double[6];
		data[0] = oldQuantityValue;
		data[1] = Double.parseDouble(txtFldQuantity.getText());
		data[2] = Double.parseDouble(lblProtein.getText());
		data[3] = Double.parseDouble(lblCarbs.getText());
		data[4] = Double.parseDouble(lblFats.getText());
		data[5] = Double.parseDouble(lblEnergy.getText());

		return data;
	}

	public void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {

		final String searchedText = txtFilSearchFood.getText().trim()
				.toLowerCase();
		cleanFormFields();
		if (searchedText.length() < 0) {
			return;
		}
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				fillForm(port.takeFood(searchedText));

			}
		});
	}

	private void fillForm(String inputToBeFilled) {
		if ("".equals(inputToBeFilled)) {
			cleanFormFields();
			return;
		}

		// 3;картофи;100;г.;1.71;20.01;0;86;328
		String[] dataForFilling = inputToBeFilled.split(";");
		// Save the old value
		changeQuantityValue(Double.parseDouble(dataForFilling[2]));
		cleanFormFields();
		lblFoodName.setText(dataForFilling[1]);
		txtFldQuantity.setText(dataForFilling[2]);
		jLabel7.setText("Количество в " + dataForFilling[3]);
		lblProtein.setText(dataForFilling[4]);
		lblCarbs.setText(dataForFilling[5]);
		lblFats.setText(dataForFilling[6]);
		lblEnergy.setText(dataForFilling[7]);

		// Fill description field
		txtAreaDescription.setText(generateDiscripton(dataForFilling));
	}

	private String generateDiscripton(String[] foodData) {
		StringBuffer result = new StringBuffer();
		result.append("Според нашите данни, в " + oldQuantityValue + " "
				+ foodData[3] + " от \nхраната\"");
		result.append(foodData[1]);
		result.append("\" се съдържа: \n");
		result.append("     -Белтък ").append(foodData[4])
				.append(" " + foodData[3] + " ").append("\n");
		result.append("     -Въглехидрати ").append(foodData[5])
				.append(" " + foodData[3] + " ").append("\n");
		result.append("     -Мазнини ").append(foodData[6])
				.append(" " + foodData[3] + " ").append("\n");
		result.append("     -Енергия ").append(foodData[7]).append(" ")
				.append("ccal").append("\n");

		return result.toString();
	}

	private void cleanFormFields() {
		lblFoodName.setText("");
		txtFldQuantity.setText("");
		jLabel7.setText("Количество");
		lblProtein.setText("");
		lblCarbs.setText("");
		lblFats.setText("");
		lblEnergy.setText("");

		// Fill description field
		txtAreaDescription.setText("");
	}

	public synchronized void changeQuantityValue(double newValue) {
		if (newValue < 0) {
			oldQuantityValue = 0;
			return;
		}
		oldQuantityValue = newValue;
	}
}
