
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package main.java.bg.fmi.food.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2013-06-01T00:18:35.493+03:00
 * Generated source version: 2.5.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "TakeFoodImplService",
                      portName = "TakeFoodImplPort",
                      targetNamespace = "http://ws.fmi.bg.java.main/",
                      wsdlLocation = "http://localhost:8080/FoodService/services/TakeFoodImplPort?wsdl",
                      endpointInterface = "main.java.bg.fmi.food.service.TakeFoodSEI")
                      
public class TakeFoodSEIImpl implements TakeFoodSEI {

    private static final Logger LOG = Logger.getLogger(TakeFoodSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see main.java.bg.fmi.food.service.TakeFoodSEI#takeFood(java.lang.String  arg0 )*
     */
    public java.lang.String takeFood(java.lang.String arg0) { 
        LOG.info("Executing operation takeFood");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-552486443";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
