
package main.java.bg.fmi.food.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2013-06-01T00:18:35.418+03:00
 * Generated source version: 2.5.10
 * 
 */
public final class TakeFoodSEI_TakeFoodImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.fmi.bg.java.main/", "TakeFoodImplService");

    private TakeFoodSEI_TakeFoodImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TakeFoodImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TakeFoodImplService ss = new TakeFoodImplService(wsdlURL, SERVICE_NAME);
        TakeFoodSEI port = ss.getTakeFoodImplPort();  
        
        {
        System.out.println("Invoking takeFood...");
        java.lang.String _takeFood_arg0 = "_takeFood_arg0-863709915";
        java.lang.String _takeFood__return = port.takeFood(_takeFood_arg0);
        System.out.println("takeFood.result=" + _takeFood__return);


        }

        System.exit(0);
    }

}
