package main.java.bg.fmi.food.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2013-06-01T00:18:35.520+03:00
 * Generated source version: 2.5.10
 * 
 */
@WebServiceClient(name = "TakeFoodImplService", 
                  wsdlLocation = "http://localhost:8080/FoodService/services/TakeFoodImplPort?wsdl",
                  targetNamespace = "http://ws.fmi.bg.java.main/") 
public class TakeFoodImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.fmi.bg.java.main/", "TakeFoodImplService");
    public final static QName TakeFoodImplPort = new QName("http://ws.fmi.bg.java.main/", "TakeFoodImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/FoodService/services/TakeFoodImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TakeFoodImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/FoodService/services/TakeFoodImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TakeFoodImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TakeFoodImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TakeFoodImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TakeFoodImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TakeFoodImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TakeFoodImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TakeFoodSEI
     */
    @WebEndpoint(name = "TakeFoodImplPort")
    public TakeFoodSEI getTakeFoodImplPort() {
        return super.getPort(TakeFoodImplPort, TakeFoodSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TakeFoodSEI
     */
    @WebEndpoint(name = "TakeFoodImplPort")
    public TakeFoodSEI getTakeFoodImplPort(WebServiceFeature... features) {
        return super.getPort(TakeFoodImplPort, TakeFoodSEI.class, features);
    }

}
